// GENERATED by `cargo xtask codegen` from crates/support/schema.
// Do not edit: your change will be overwritten and CI will fail on the diff.

/// One row per operation, emitted from the contract.
pub(crate) struct GeneratedOperation {
    pub id: &'static str,
    pub method: &'static str,
    pub path: &'static str,
    pub cli: &'static str,
    pub summary: &'static str,
    pub idempotent: bool,
    pub dry_runnable: bool,
}

/// Every operation this Runtime serves. `/v1/meta` renders this verbatim,
/// so an agent planning against it is planning against the contract itself.
pub(crate) const OPERATIONS: &[GeneratedOperation] = &[
    GeneratedOperation {
        id: "node.status",
        method: "GET",
        path: "/health",
        cli: "fn node status",
        summary: "Liveness and version of this Node.",
        idempotent: true,
        dry_runnable: false,
    },
    GeneratedOperation {
        id: "node.meta",
        method: "GET",
        path: "/v1/meta",
        cli: "fn node meta",
        summary: "The machine-readable description of this Node's surface.",
        idempotent: true,
        dry_runnable: false,
    },
    GeneratedOperation {
        id: "society.list",
        method: "GET",
        path: "/v1/societies",
        cli: "fn society list",
        summary: "Every Society this Node holds.",
        idempotent: true,
        dry_runnable: false,
    },
    GeneratedOperation {
        id: "society.create",
        method: "POST",
        path: "/v1/societies",
        cli: "fn society create",
        summary: "Found a Society.",
        idempotent: true,
        dry_runnable: true,
    },
    GeneratedOperation {
        id: "society.get",
        method: "GET",
        path: "/v1/societies/{society_id}",
        cli: "fn society get",
        summary: "Read one Society.",
        idempotent: true,
        dry_runnable: false,
    },
];

/// The closed error registry. HTTP status per code.
pub(crate) const ERROR_STATUS: &[(&str, u16)] = &[
    ("usage", 400),
    ("invalid_identifier", 400),
    ("invalid_handle", 400),
    ("invalid_fnid", 400),
    ("unauthenticated", 401),
    ("capability_denied", 403),
    ("confirmation_required", 403),
    ("not_found", 404),
    ("conflict", 409),
    ("rejected", 422),
    ("rate_limited", 429),
    ("store_unavailable", 500),
    ("internal", 500),
];
