//! Schema-first code generation (M0.4, `docs/41 §12`).
//!
//! Reads `fractal-schema` and writes every dependent surface. `--check`
//! regenerates into memory and diffs, so a hand-edit to a generated file is a
//! build failure rather than a surprise three weeks later.
//!
//! This is the mechanism that turns P13 from a review checklist into a build
//! gate. The CLI command tree is not written by a person who might forget an
//! operation; it is emitted from the same table the HTTP router is emitted from.

use anyhow::{bail, Context as _, Result};
use fractal_schema as sch;
use serde_json::{json, Map, Value};
use std::fmt::Write as _;
use std::path::PathBuf;

const BANNER: &str = "GENERATED by `cargo xtask codegen` from crates/support/schema.\nDo not edit: your change will be overwritten and CI will fail on the diff.";

pub(crate) fn run(check: bool) -> Result<()> {
    validate()?;

    let root = crate::root();
    // Generated Rust is passed through rustfmt before it is written. Without
    // this, `cargo fmt` reformats these files and the next `codegen --check`
    // reports drift that nobody caused — two gates disagreeing about the same
    // bytes, which would train people to ignore both.
    let mut outputs: Vec<(PathBuf, String)> = vec![
        (root.join("schemas/openapi/v1.json"), openapi()?),
        (
            root.join("crates/api/http/src/generated.rs"),
            rustfmt(&api_table())?,
        ),
        (
            root.join("crates/bin/cli/src/generated.rs"),
            rustfmt(&cli_tree())?,
        ),
        (root.join("packages/api-client/src/index.ts"), ts_client()),
        (root.join("packages/api-client/dist/index.js"), js_client()),
    ];
    for e in sch::EVENTS {
        outputs.push((
            root.join(format!("schemas/events/{}.json", e.kind)),
            event_schema(e)?,
        ));
    }

    let mut drift = Vec::new();
    for (path, content) in &outputs {
        if check {
            if std::fs::read_to_string(path).unwrap_or_default() != *content {
                drift.push(path.clone());
            }
        } else {
            if let Some(dir) = path.parent() {
                std::fs::create_dir_all(dir)?;
            }
            std::fs::write(path, content).with_context(|| format!("writing {}", path.display()))?;
        }
    }

    if check {
        if drift.is_empty() {
            println!("codegen: {} artefacts, 0 drift", outputs.len());
            return Ok(());
        }
        for p in &drift {
            eprintln!(
                "  ✕ out of date: {}",
                p.strip_prefix(&root).unwrap_or(p).display()
            );
        }
        bail!("codegen drift — run `cargo xtask codegen` and commit the result");
    }
    println!("codegen: wrote {} artefacts", outputs.len());
    Ok(())
}

/// Run generated Rust through rustfmt so `cargo fmt` has nothing left to change.
fn rustfmt(src: &str) -> Result<String> {
    use std::io::Write as _;
    use std::process::{Command, Stdio};

    let mut child = Command::new("rustfmt")
        .args(["--edition", "2021", "--emit", "stdout", "--quiet"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
        .context("spawning rustfmt — is the toolchain component installed?")?;
    child
        .stdin
        .take()
        .context("rustfmt stdin")?
        .write_all(src.as_bytes())
        .context("writing to rustfmt")?;
    let out = child.wait_with_output().context("waiting for rustfmt")?;
    if !out.status.success() {
        bail!(
            "rustfmt rejected generated code — the generator emitted something that does not parse"
        );
    }
    String::from_utf8(out.stdout).context("rustfmt produced non-UTF-8")
}

/// Contract rules that a type system cannot express.
///
/// The first of these is the important one: **an operation without a CLI binding
/// cannot exist.** That single check is P13.
fn validate() -> Result<()> {
    let mut problems = Vec::new();

    for op in sch::OPERATIONS {
        if op.cli.noun.is_empty() || op.cli.verb.is_empty() {
            problems.push(format!(
                "{}: no CLI binding — every operation must have one (P13)",
                op.id
            ));
        }
        let expected = format!("{}.{}", op.cli.noun, op.cli.verb);
        if op.id != expected {
            problems.push(format!(
                "{}: id must equal `<noun>.<verb>`, which would be `{expected}`",
                op.id
            ));
        }
        if let Some(r) = op.request {
            if sch::type_def(r).is_none() {
                problems.push(format!("{}: request type `{r}` is not declared", op.id));
            }
        }
        if sch::type_def(op.response).is_none() {
            problems.push(format!(
                "{}: response type `{}` is not declared",
                op.id, op.response
            ));
        }
        for code in op.errors {
            if sch::error_def(code).is_none() {
                problems.push(format!("{}: error `{code}` is not in the registry", op.id));
            }
        }
        if op.dry_runnable && op.method == sch::Method::Get {
            problems.push(format!(
                "{}: a read cannot be dry-run — it emits nothing already",
                op.id
            ));
        }
    }

    for e in sch::EVENTS {
        if sch::type_def(e.payload).is_none() {
            problems.push(format!(
                "{}: payload type `{}` is not declared",
                e.kind, e.payload
            ));
        }
        if !e.kind.ends_with(&format!(".v{}", e.version)) {
            problems.push(format!(
                "{}: kind must end with `.v{}` (`docs/10 §5`)",
                e.kind, e.version
            ));
        }
    }

    if problems.is_empty() {
        return Ok(());
    }
    for p in &problems {
        eprintln!("  ✕ {p}");
    }
    bail!(
        "{} contract violation(s) in crates/support/schema",
        problems.len()
    )
}

// ---------------------------------------------------------------------------
// OpenAPI 3.1
// ---------------------------------------------------------------------------

fn schema_for(ty: sch::Ty) -> Value {
    match ty {
        sch::Ty::Str => json!({ "type": "string" }),
        sch::Ty::Int => json!({ "type": "integer", "format": "int64" }),
        sch::Ty::Bool => json!({ "type": "boolean" }),
        sch::Ty::Timestamp => {
            json!({ "type": "integer", "format": "int64", "description": "Milliseconds since the Unix epoch, UTC." })
        }
        sch::Ty::Quanta => json!({
            "type": "string",
            "pattern": r"^-?\d+\.\d{9}$",
            "description": "An amount of Fraction, as a decimal string with exactly nine places. A JSON number would round it."
        }),
        sch::Ty::Enum(values) => json!({ "type": "string", "enum": values }),
        sch::Ty::Ref(name) => json!({ "$ref": format!("#/components/schemas/{name}") }),
    }
}

fn type_schema(t: &sch::TypeDef) -> Value {
    let mut props = Map::new();
    let mut required = Vec::new();
    for f in t.fields {
        // A field typed as a Ref inside a list type is an array of that type.
        // `SocietyList.societies` is the only case today; keeping the rule
        // explicit here beats adding a variant nobody else needs.
        let is_list = t.name.ends_with("List");
        let mut s = schema_for(f.ty);
        if is_list && matches!(f.ty, sch::Ty::Ref(_)) {
            s = json!({ "type": "array", "items": s });
        }
        if let Some(obj) = s.as_object_mut() {
            obj.insert("description".to_owned(), json!(f.doc));
        }
        props.insert(f.name.to_owned(), s);
        if f.required {
            required.push(f.name);
        }
    }
    json!({
        "type": "object",
        "description": t.doc,
        "properties": props,
        "required": required,
        "additionalProperties": false,
    })
}

/// The response map for one operation: its success shape plus every error it
/// declares. Errors with `http: 0` are client-side only and have no HTTP shape.
fn responses_for(op: &sch::Operation) -> Map<String, Value> {
    let mut responses = Map::new();
    responses.insert(
        if op.method == sch::Method::Post {
            "201".to_owned()
        } else {
            "200".to_owned()
        },
        json!({
            "description": op.summary,
            "content": { "application/json": { "schema": {
                "type": "object",
                "properties": {
                    "ok": { "const": true },
                    "data": { "$ref": format!("#/components/schemas/{}", op.response) },
                    "meta": { "type": "object" },
                    "warnings": { "type": "array", "items": { "type": "string" } }
                },
                "required": ["ok", "data", "meta"]
            }}}
        }),
    );
    for code in op.errors {
        let Some(e) = sch::error_def(code) else {
            continue;
        };
        if e.http == 0 {
            continue;
        }
        responses.entry(e.http.to_string()).or_insert_with(|| {
            json!({
                "description": e.doc,
                "content": { "application/json": { "schema": {
                    "type": "object",
                    "properties": { "ok": { "const": false }, "error": { "$ref": "#/components/schemas/Error" } },
                    "required": ["ok", "error"]
                }}}
            })
        });
    }
    responses
}

/// The `{param}` in a path, if it has one. Paths take at most one.
fn path_param(path: &str) -> Option<&str> {
    let start = path.find('{')?;
    let rest = path.get(start + 1..)?;
    let end = rest.find('}')?;
    rest.get(..end)
}

fn operation_item(op: &sch::Operation) -> Value {
    let mut item = json!({
        "operationId": op.id,
        "summary": op.summary,
        "responses": responses_for(op),
        "x-fractal-cli": format!("fn {} {}", op.cli.noun, op.cli.verb),
        "x-fractal-idempotent": op.idempotent,
        "x-fractal-dry-runnable": op.dry_runnable,
    });
    let Some(o) = item.as_object_mut() else {
        return json!({});
    };
    if let Some(cap) = op.capability {
        o.insert("x-fractal-capability".to_owned(), json!(cap));
    }
    if let Some(name) = path_param(op.path) {
        o.insert(
            "parameters".to_owned(),
            json!([{ "name": name, "in": "path", "required": true, "schema": { "type": "string" } }]),
        );
    }
    if let Some(req) = op.request {
        o.insert(
            "requestBody".to_owned(),
            json!({
                "required": true,
                "content": { "application/json": {
                    "schema": { "$ref": format!("#/components/schemas/{req}") } } }
            }),
        );
    }
    item
}

fn error_schema() -> Value {
    json!({
        "type": "object",
        "description": "Cause, then remedy, no apology (docs/33 §7.3).",
        "properties": {
            "code": { "type": "string", "enum": sch::ERRORS.iter().map(|e| e.code).collect::<Vec<_>>() },
            "title": { "type": "string" },
            "detail": { "type": "string", "description": "What happened, specifically." },
            "remedy": { "type": "object", "properties": { "human": { "type": "string" } },
                        "description": "What to do about it." },
            "retryable": { "type": "boolean" },
            "docs": { "type": "string", "format": "uri" }
        },
        "required": ["code", "title", "detail", "retryable"],
    })
}

fn openapi() -> Result<String> {
    let mut schemas = Map::new();
    for t in sch::TYPES {
        schemas.insert(t.name.to_owned(), type_schema(t));
    }
    schemas.insert("Error".to_owned(), error_schema());

    let mut paths: Map<String, Value> = Map::new();
    for op in sch::OPERATIONS {
        let entry = paths.entry(op.path.to_owned()).or_insert_with(|| json!({}));
        if let Some(o) = entry.as_object_mut() {
            o.insert(op.method.openapi().to_owned(), operation_item(op));
        }
    }

    let doc = json!({
        "openapi": "3.1.0",
        "info": { "title": "Fractal Node", "version": sch::API_VERSION, "description": BANNER },
        "paths": paths,
        "components": { "schemas": schemas },
    });
    Ok(format!("{}\n", serde_json::to_string_pretty(&doc)?))
}

fn event_schema(e: &sch::EventDef) -> Result<String> {
    let Some(payload) = sch::type_def(e.payload) else {
        bail!("{}: payload type missing", e.kind)
    };
    let doc = json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": format!("https://schemas.fractalnode.dev/events/{}.json", e.kind),
        "title": e.kind,
        "description": format!("{}\n\n{}", e.doc, BANNER),
        "x-fractal-version": e.version,
        "type": "object",
        "properties": type_schema(payload).get("properties").cloned().unwrap_or(json!({})),
        "required": type_schema(payload).get("required").cloned().unwrap_or(json!([])),
        "additionalProperties": false,
    });
    Ok(format!("{}\n", serde_json::to_string_pretty(&doc)?))
}

// ---------------------------------------------------------------------------
// Rust: the operation table the gateway serves from /v1/meta
// ---------------------------------------------------------------------------

fn api_table() -> String {
    let mut out = String::new();
    for l in BANNER.lines() {
        let _ = writeln!(out, "// {l}");
    }
    out.push_str("\n/// One row per operation, emitted from the contract.\n");
    out.push_str("pub(crate) struct GeneratedOperation {\n    pub id: &'static str,\n    pub method: &'static str,\n    pub path: &'static str,\n    pub cli: &'static str,\n    pub summary: &'static str,\n    pub idempotent: bool,\n    pub dry_runnable: bool,\n}\n\n");
    out.push_str("/// Every operation this Runtime serves. `/v1/meta` renders this verbatim,\n/// so an agent planning against it is planning against the contract itself.\n");
    let _ = writeln!(
        out,
        "pub(crate) const OPERATIONS: &[GeneratedOperation] = &["
    );
    for op in sch::OPERATIONS {
        let _ = writeln!(
            out,
            "    GeneratedOperation {{ id: {:?}, method: {:?}, path: {:?}, cli: {:?}, summary: {:?}, idempotent: {}, dry_runnable: {} }},",
            op.id, op.method.as_str(), op.path,
            format!("fn {} {}", op.cli.noun, op.cli.verb),
            op.summary, op.idempotent, op.dry_runnable
        );
    }
    out.push_str("];\n\n");

    out.push_str("/// The closed error registry. HTTP status per code.\n");
    let _ = writeln!(out, "pub(crate) const ERROR_STATUS: &[(&str, u16)] = &[");
    for e in sch::ERRORS {
        if e.http == 0 {
            continue;
        }
        let _ = writeln!(out, "    ({:?}, {}),", e.code, e.http);
    }
    out.push_str("];\n");
    out
}

// ---------------------------------------------------------------------------
// Rust: the CLI command tree
// ---------------------------------------------------------------------------

fn cli_tree() -> String {
    let mut out = String::new();
    for l in BANNER.lines() {
        let _ = writeln!(out, "// {l}");
    }
    out.push_str("\n/// A command, emitted from the contract. `fn schema` renders these, and the\n/// dispatcher matches on `id` — so an operation cannot exist in the API and be\n/// missing here (P13).\n");
    out.push_str("pub(crate) struct GeneratedCommand {\n    pub id: &'static str,\n    pub noun: &'static str,\n    pub verb: &'static str,\n    pub args: &'static [&'static str],\n    pub flags: &'static [&'static str],\n    pub summary: &'static str,\n    pub method: &'static str,\n    pub path: &'static str,\n    pub dry_runnable: bool,\n}\n\n");
    let _ = writeln!(out, "pub(crate) const COMMANDS: &[GeneratedCommand] = &[");
    for op in sch::OPERATIONS {
        let _ = writeln!(
            out,
            "    GeneratedCommand {{ id: {:?}, noun: {:?}, verb: {:?}, args: &{:?}, flags: &{:?}, summary: {:?}, method: {:?}, path: {:?}, dry_runnable: {} }},",
            op.id, op.cli.noun, op.cli.verb, op.cli.args, op.cli.flags,
            op.summary, op.method.as_str(), op.path, op.dry_runnable
        );
    }
    out.push_str("];\n\n");

    out.push_str("/// Exit codes, from the contract. Stable forever: scripts depend on them.\n");
    let _ = writeln!(out, "pub(crate) const EXIT_CODES: &[(&str, i32)] = &[");
    for e in sch::ERRORS {
        let _ = writeln!(out, "    ({:?}, {}),", e.code, e.exit);
    }
    out.push_str("];\n\n");
    out.push_str("/// Look up the exit code for an error, defaulting to 1 (generic failure).\npub(crate) fn exit_code_for(code: &str) -> i32 {\n    let mut i = 0;\n    while i < EXIT_CODES.len() {\n        if let Some((c, e)) = EXIT_CODES.get(i) {\n            if *c == code {\n                return *e;\n            }\n        }\n        i += 1;\n    }\n    1\n}\n");
    out
}

// ---------------------------------------------------------------------------
// TypeScript client
// ---------------------------------------------------------------------------

fn ts_type(ty: sch::Ty, in_list: bool) -> String {
    let base = match ty {
        sch::Ty::Str | sch::Ty::Quanta => "string".to_owned(),
        sch::Ty::Int | sch::Ty::Timestamp => "number".to_owned(),
        sch::Ty::Bool => "boolean".to_owned(),
        sch::Ty::Enum(values) => values
            .iter()
            .map(|v| format!("'{v}'"))
            .collect::<Vec<_>>()
            .join(" | "),
        sch::Ty::Ref(name) => name.to_owned(),
    };
    if in_list {
        format!("{base}[]")
    } else {
        base
    }
}

fn ts_client() -> String {
    let mut out = String::new();
    for l in BANNER.lines() {
        let _ = writeln!(out, "// {l}");
    }
    out.push_str("//\n// The web GUI and every TypeScript consumer talk to the Node through this.\n// Hand-written fetch calls in a client are a lint failure (P3): the point of a\n// generated client is that a client cannot reach an endpoint the contract does\n// not describe.\n\n");

    for t in sch::TYPES {
        let _ = writeln!(out, "/** {} */\nexport interface {} {{", t.doc, t.name);
        for f in t.fields {
            let in_list = t.name.ends_with("List") && matches!(f.ty, sch::Ty::Ref(_));
            let opt = if f.required { "" } else { "?" };
            let _ = writeln!(
                out,
                "  /** {} */\n  {}{}: {};",
                f.doc,
                f.name,
                opt,
                ts_type(f.ty, in_list)
            );
        }
        out.push_str("}\n\n");
    }

    let codes = sch::ERRORS
        .iter()
        .map(|e| format!("'{}'", e.code))
        .collect::<Vec<_>>()
        .join(" | ");
    let _ = writeln!(out, "export type ErrorCode = {codes};\n");
    out.push_str("export interface ApiError {\n  code: ErrorCode;\n  title: string;\n  /** What happened, specifically. */\n  detail: string;\n  /** What to do about it. */\n  remedy?: { human: string };\n  retryable: boolean;\n  docs?: string;\n}\n\n");
    out.push_str("export interface Envelope<T> {\n  ok: true;\n  data: T;\n  meta: Record<string, unknown>;\n  warnings: string[];\n}\n\n");
    out.push_str("export class FractalError extends Error {\n  constructor(public readonly error: ApiError) {\n    super(error.detail || error.title);\n    this.name = 'FractalError';\n  }\n}\n\n");
    out.push_str("export interface ClientOptions {\n  /** Base URL. Defaults to the origin serving the page. */\n  baseUrl?: string;\n  fetch?: typeof globalThis.fetch;\n}\n\n");
    out.push_str("export function createClient(options: ClientOptions = {}) {\n  const base = options.baseUrl ?? '';\n  const f = options.fetch ?? globalThis.fetch.bind(globalThis);\n\n  async function call<T>(method: string, path: string, body?: unknown): Promise<T> {\n    const res = await f(base + path, {\n      method,\n      headers: body ? { 'content-type': 'application/json' } : {},\n      body: body ? JSON.stringify(body) : undefined,\n    });\n    const json = await res.json().catch(() => null);\n    if (json && json.ok === true) return json.data as T;\n    throw new FractalError(\n      (json && json.error) ?? {\n        code: 'internal',\n        title: 'The Node sent something that is not JSON',\n        detail: `HTTP ${res.status}`,\n        retryable: false,\n      },\n    );\n  }\n\n  return {\n");

    for op in sch::OPERATIONS {
        let fn_name = camel(&format!("{}_{}", op.cli.noun, op.cli.verb));
        let path_param = op.path.find('{').and_then(|s| {
            op.path[s..]
                .find('}')
                .map(|e| op.path[s + 1..s + e].to_owned())
        });
        let mut args = Vec::new();
        if let Some(p) = &path_param {
            args.push(format!("{}: string", camel(p)));
        }
        if let Some(req) = op.request {
            args.push(format!("body: {req}"));
        }
        let path_expr = path_param.as_ref().map_or_else(
            || format!("'{}'", op.path),
            |p| {
                format!(
                    "`{}`",
                    op.path
                        .replace(&format!("{{{p}}}"), &format!("${{{}}}", camel(p)))
                )
            },
        );
        let body_arg = if op.request.is_some() { ", body" } else { "" };
        let _ = writeln!(out, "    /** {} */", op.summary);
        let _ = writeln!(
            out,
            "    {fn_name}: ({}): Promise<{}> =>\n      call<{}>('{}', {path_expr}{body_arg}),",
            args.join(", "),
            op.response,
            op.response,
            op.method.as_str()
        );
    }
    out.push_str("  };\n}\n\nexport type FractalClient = ReturnType<typeof createClient>;\n");
    out
}

/// A plain-ESM twin of the TypeScript client.
///
/// PH0 serves the web GUI as static files with no build step, so it cannot
/// import `.ts`. Emitting both from the same table keeps the rule intact — no
/// client hand-writes a fetch call — without dragging a bundler into Phase 0.
/// PH1 builds the web app with Vite and this file goes away (`docs/51`).
fn js_client() -> String {
    let mut out = String::new();
    for l in BANNER.lines() {
        let _ = writeln!(out, "// {l}");
    }
    out.push_str("//\n// Plain ESM twin of ../src/index.ts. Same contract, no build step.\n\n");
    out.push_str("export class FractalError extends Error {\n  constructor(error) {\n    super(error.detail || error.title);\n    this.name = 'FractalError';\n    this.error = error;\n  }\n}\n\n");
    out.push_str("export function createClient(options = {}) {\n  const base = options.baseUrl ?? '';\n  const f = options.fetch ?? globalThis.fetch.bind(globalThis);\n\n  async function call(method, path, body) {\n    const res = await f(base + path, {\n      method,\n      headers: body ? { 'content-type': 'application/json' } : {},\n      body: body ? JSON.stringify(body) : undefined,\n    });\n    const json = await res.json().catch(() => null);\n    if (json && json.ok === true) return json.data;\n    throw new FractalError(\n      (json && json.error) ?? {\n        code: 'internal',\n        title: 'The Node sent something that is not JSON',\n        detail: `HTTP ${res.status}`,\n        retryable: false,\n      },\n    );\n  }\n\n  return {\n");
    for op in sch::OPERATIONS {
        let fn_name = camel(&format!("{}_{}", op.cli.noun, op.cli.verb));
        let param = path_param(op.path).map(camel);
        let mut args = Vec::new();
        if let Some(p) = &param {
            args.push(p.clone());
        }
        if op.request.is_some() {
            args.push("body".to_owned());
        }
        let path_expr = param.as_ref().map_or_else(
            || format!("'{}'", op.path),
            |p| {
                let raw = path_param(op.path).unwrap_or("");
                format!(
                    "`{}`",
                    op.path.replace(&format!("{{{raw}}}"), &format!("${{{p}}}"))
                )
            },
        );
        let body_arg = if op.request.is_some() { ", body" } else { "" };
        let _ = writeln!(out, "    /** {} */", op.summary);
        let _ = writeln!(
            out,
            "    {fn_name}: ({}) => call('{}', {path_expr}{body_arg}),",
            args.join(", "),
            op.method.as_str()
        );
    }
    out.push_str("  };\n}\n");
    out
}

fn camel(s: &str) -> String {
    let mut out = String::new();
    let mut upper = false;
    for c in s.chars() {
        if c == '_' || c == '-' {
            upper = true;
        } else if upper {
            out.extend(c.to_uppercase());
            upper = false;
        } else {
            out.push(c);
        }
    }
    out
}
