//! The design-token pipeline (N7, `docs/32 §2`).
//!
//! One hand-authored source, five generated targets. The `--check` mode
//! regenerates and diffs, so drift between web, desktop, CLI, iOS and Android is
//! not discouraged — it is impossible.

use anyhow::{bail, Context as _, Result};
use serde_json::Value;
use std::fmt::Write as _;

const HEADER: &str = "GENERATED by `cargo xtask tokens` from packages/tokens/tokens.json.\nDo not edit. A colour that is not a token cannot ship (docs/32 §2).";

pub(crate) fn run(check: bool) -> Result<()> {
    let root = crate::root();
    let src = root.join("packages/tokens/tokens.json");
    let raw =
        std::fs::read_to_string(&src).with_context(|| format!("reading {}", src.display()))?;
    let doc: Value = serde_json::from_str(&raw)?;

    let outputs = vec![
        (root.join("packages/tokens/dist/tokens.css"), css(&doc)?),
        (root.join("packages/tokens/dist/tokens.rs"), rust(&doc)?),
        (
            root.join("packages/tokens/dist/tokens.ansi.json"),
            ansi(&doc)?,
        ),
        (root.join("packages/tokens/dist/Tokens.swift"), swift(&doc)?),
        (root.join("packages/tokens/dist/Tokens.kt"), kotlin(&doc)?),
    ];

    let mut drifted = Vec::new();
    for (path, content) in &outputs {
        if check {
            let current = std::fs::read_to_string(path).unwrap_or_default();
            if current != *content {
                drifted.push(path.clone());
            }
        } else {
            if let Some(parent) = path.parent() {
                std::fs::create_dir_all(parent)?;
            }
            std::fs::write(path, content)?;
        }
    }

    if check {
        if drifted.is_empty() {
            println!("tokens: 5 targets, 0 drift");
            return Ok(());
        }
        for p in &drifted {
            eprintln!(
                "  ✕ out of date: {}",
                p.strip_prefix(&root).unwrap_or(p).display()
            );
        }
        bail!("token drift — run `cargo xtask tokens` and commit the result");
    }
    println!("tokens: wrote {} targets", outputs.len());
    Ok(())
}

fn colors(doc: &Value) -> Result<&serde_json::Map<String, Value>> {
    doc.pointer("/core/color")
        .and_then(Value::as_object)
        .context("tokens.json has no /core/color")
}

fn value_of(v: &Value) -> String {
    v.get("value")
        .and_then(Value::as_str)
        .or_else(|| v.as_str())
        .unwrap_or("")
        .to_owned()
}

fn css(doc: &Value) -> Result<String> {
    let mut out = String::new();
    for line in HEADER.lines() {
        let _ = writeln!(out, "/* {line} */");
    }
    out.push_str("\n:root {\n");
    for (k, v) in colors(doc)? {
        let _ = writeln!(out, "  --fn-c-{k}: {};", value_of(v));
    }
    if let Some(lines) = doc.pointer("/core/line").and_then(Value::as_object) {
        for (k, v) in lines {
            let name = if k == "base" {
                "line".to_owned()
            } else {
                format!("line-{k}")
            };
            let _ = writeln!(out, "  --fn-c-{name}: {};", value_of(v));
        }
    }
    if let Some(space) = doc.pointer("/core/space").and_then(Value::as_object) {
        for (k, v) in space {
            let _ = writeln!(out, "  --fn-space-{k}: {};", value_of(v));
        }
    }
    if let Some(r) = doc.pointer("/core/radius").and_then(Value::as_object) {
        for (k, v) in r {
            let _ = writeln!(out, "  --fn-radius-{k}: {};", value_of(v));
        }
    }
    if let Some(d) = doc.pointer("/core/duration").and_then(Value::as_object) {
        for (k, v) in d {
            let _ = writeln!(out, "  --fn-dur-{k}: {};", value_of(v));
        }
    }
    if let Some(e) = doc.pointer("/core/ease").and_then(Value::as_object) {
        for (k, v) in e {
            let _ = writeln!(out, "  --fn-ease-{k}: {};", value_of(v));
        }
    }
    if let Some(f) = doc.pointer("/core/font").and_then(Value::as_object) {
        for (k, v) in f {
            let _ = writeln!(out, "  --fn-font-{k}: {};", value_of(v));
        }
    }
    out.push('\n');
    if let Some(sem) = doc.get("semantic").and_then(Value::as_object) {
        for (k, v) in sem {
            let Some(pointer) = v.as_str() else { continue };
            let leaf = pointer.rsplit('.').next().unwrap_or_default();
            let _ = writeln!(out, "  --fn-{k}: var(--fn-c-{leaf});");
        }
    }
    out.push_str("}\n");
    Ok(out)
}

fn rust(doc: &Value) -> Result<String> {
    let mut out = String::new();
    for line in HEADER.lines() {
        let _ = writeln!(out, "// {line}");
    }
    out.push_str("\n#![allow(dead_code)]\n\n/// LATTICE colours as 24-bit RGB.\npub mod color {\n");
    for (k, v) in colors(doc)? {
        let hex = value_of(v);
        if let Some(h) = hex.strip_prefix('#') {
            if h.len() == 6 {
                let r = u8::from_str_radix(&h[0..2], 16).unwrap_or(0);
                let g = u8::from_str_radix(&h[2..4], 16).unwrap_or(0);
                let b = u8::from_str_radix(&h[4..6], 16).unwrap_or(0);
                let name = k.to_uppercase().replace('-', "_");
                let _ = writeln!(
                    out,
                    "    /// `{hex}`\n    pub const {name}: (u8, u8, u8) = ({r}, {g}, {b});"
                );
            }
        }
    }
    out.push_str("}\n");
    Ok(out)
}

fn ansi(doc: &Value) -> Result<String> {
    let term = doc
        .get("terminal")
        .context("tokens.json has no /terminal")?;
    let mut wrapped = serde_json::Map::new();
    wrapped.insert(
        "$generated".to_owned(),
        Value::String(HEADER.replace('\n', " ")),
    );
    if let Some(obj) = term.as_object() {
        for (k, v) in obj {
            if k.starts_with('$') {
                continue;
            }
            wrapped.insert(k.clone(), v.clone());
        }
    }
    Ok(format!(
        "{}\n",
        serde_json::to_string_pretty(&Value::Object(wrapped))?
    ))
}

// SwiftUI's Color takes 0.0–1.0 components, so the generator converts. This is
// the one place float arithmetic is permitted in the workspace: it is a build
// tool emitting a literal, never a value the ledger or the domain will see.
#[allow(clippy::float_arithmetic)]
fn swift(doc: &Value) -> Result<String> {
    let mut out = String::new();
    for line in HEADER.lines() {
        let _ = writeln!(out, "// {line}");
    }
    out.push_str("\nimport SwiftUI\n\npublic enum FNColor {\n");
    for (k, v) in colors(doc)? {
        let hex = value_of(v);
        if let Some(h) = hex.strip_prefix('#') {
            if h.len() == 6 {
                let name = camel(k);
                let r = f64::from(u8::from_str_radix(&h[0..2], 16).unwrap_or(0)) / 255.0;
                let g = f64::from(u8::from_str_radix(&h[2..4], 16).unwrap_or(0)) / 255.0;
                let b = f64::from(u8::from_str_radix(&h[4..6], 16).unwrap_or(0)) / 255.0;
                let _ = writeln!(out, "    /// `{hex}`\n    public static let {name} = Color(red: {r:.4}, green: {g:.4}, blue: {b:.4})");
            }
        }
    }
    out.push_str("}\n");
    Ok(out)
}

fn kotlin(doc: &Value) -> Result<String> {
    let mut out = String::new();
    for line in HEADER.lines() {
        let _ = writeln!(out, "// {line}");
    }
    out.push_str("\npackage dev.fractalnode.tokens\n\nimport androidx.compose.ui.graphics.Color\n\nobject FNColor {\n");
    for (k, v) in colors(doc)? {
        let hex = value_of(v);
        if let Some(h) = hex.strip_prefix('#') {
            if h.len() == 6 {
                let _ = writeln!(
                    out,
                    "    /// `{hex}`\n    val {} = Color(0xFF{})",
                    camel(k),
                    h.to_uppercase()
                );
            }
        }
    }
    out.push_str("}\n");
    Ok(out)
}

fn camel(k: &str) -> String {
    let mut out = String::new();
    let mut upper = false;
    for c in k.chars() {
        if c == '-' {
            upper = true;
        } else if upper {
            out.extend(c.to_uppercase());
            upper = false;
        } else {
            out.push(c);
        }
    }
    out
}
