// GENERATED by `cargo xtask codegen` from crates/support/schema.
// Do not edit: your change will be overwritten and CI will fail on the diff.
//
// The web GUI and every TypeScript consumer talk to the Node through this.
// Hand-written fetch calls in a client are a lint failure (P3): the point of a
// generated client is that a client cannot reach an endpoint the contract does
// not describe.

/** Liveness and version of a Node. */
export interface Health {
  /** Whether the Runtime considers itself healthy. */
  status: 'ok' | 'degraded';
  /** Runtime version. */
  runtime: string;
  /** API major version. */
  api_version: string;
}

/** A Society — the atomic container (P1). */
export interface Society {
  /** `soc_` + ULID. */
  society_id: string;
  /** Display name, 1–64 characters. */
  name: string;
  /** Globally unique, `@name`. */
  handle: string;
  /** FNID of the founding Citizen. */
  founder: string;
  /** Who may see and join it. */
  visibility: 'public' | 'discoverable' | 'private' | 'sealed';
  /** Lifecycle state (`docs/11 §4`). */
  status: 'forming' | 'active' | 'dormant' | 'fracturing' | 'dissolving' | 'archived';
  /** Members. Never below 1 while Active. */
  member_count: number;
  /** When it was founded. */
  created_at: number;
  /** Position in THIS Society's log. Per-Society, never global (`docs/10 §4`). */
  seq: number;
}

/** Found a Society. */
export interface CreateSocietyRequest {
  /** Display name, 1–64 characters. */
  name: string;
  /** 3–24 characters of a–z, 0–9, underscore. */
  handle: string;
  /** Defaults to discoverable. */
  visibility?: 'public' | 'discoverable' | 'private' | 'sealed';
  /** Makes the command safe to retry for 24 hours (`docs/10 §10`). */
  idempotency_key?: string;
  /** PH0 only. From PH1 the actor comes from the session (`docs/12`). */
  founder_fnid?: string;
  /** PH0 only. How many this Citizen has already founded; the first-hearth rule reads it. */
  societies_founded?: number;
  /** PH0 only. Founding a second Society requires Level 3. */
  founder_level?: number;
}

/** Every Society on this Node. */
export interface SocietyList {
  /** Ordered by creation time. */
  societies: Society[];
}

/** A single Society. */
export interface SocietyEnvelope {
  /** The Society. */
  society: Society;
}

/** The machine-readable description of this Node's surface (`docs/31 §8`). */
export interface Meta {
  /** Runtime version. */
  runtime: string;
  /** API major version. */
  api_version: string;
  /** The phase this build implements. */
  phase: string;
  /** Every operation, generated from the schema. An agent plans against this rather than probing. */
  operations: string;
}

/** Payload of `society.created.v1`. */
export interface SocietyCreatedPayload {
  /** `soc_` + ULID. */
  society_id: string;
  /** Display name as founded. */
  name: string;
  /** Handle as claimed. */
  handle: string;
  /** FNID of the founding Citizen. */
  founder: string;
  /** Visibility at founding. */
  visibility: 'public' | 'discoverable' | 'private' | 'sealed';
  /** A Society is Active from its first event: it has one member, its founder. */
  status: 'active';
  /** How this Society came to exist (`docs/11 §2.2` Lineage). */
  origin: 'first_hearth' | 'founded' | 'crystallized' | 'fractured' | 'forked';
}

export type ErrorCode = 'usage' | 'invalid_identifier' | 'invalid_handle' | 'invalid_fnid' | 'unauthenticated' | 'capability_denied' | 'confirmation_required' | 'not_found' | 'conflict' | 'rejected' | 'rate_limited' | 'store_unavailable' | 'unreachable' | 'internal';

export interface ApiError {
  code: ErrorCode;
  title: string;
  /** What happened, specifically. */
  detail: string;
  /** What to do about it. */
  remedy?: { human: string };
  retryable: boolean;
  docs?: string;
}

export interface Envelope<T> {
  ok: true;
  data: T;
  meta: Record<string, unknown>;
  warnings: string[];
}

export class FractalError extends Error {
  constructor(public readonly error: ApiError) {
    super(error.detail || error.title);
    this.name = 'FractalError';
  }
}

export interface ClientOptions {
  /** Base URL. Defaults to the origin serving the page. */
  baseUrl?: string;
  fetch?: typeof globalThis.fetch;
}

export function createClient(options: ClientOptions = {}) {
  const base = options.baseUrl ?? '';
  const f = options.fetch ?? globalThis.fetch.bind(globalThis);

  async function call<T>(method: string, path: string, body?: unknown): Promise<T> {
    const res = await f(base + path, {
      method,
      headers: body ? { 'content-type': 'application/json' } : {},
      body: body ? JSON.stringify(body) : undefined,
    });
    const json = await res.json().catch(() => null);
    if (json && json.ok === true) return json.data as T;
    throw new FractalError(
      (json && json.error) ?? {
        code: 'internal',
        title: 'The Node sent something that is not JSON',
        detail: `HTTP ${res.status}`,
        retryable: false,
      },
    );
  }

  return {
    /** Liveness and version of this Node. */
    nodeStatus: (): Promise<Health> =>
      call<Health>('GET', '/health'),
    /** The machine-readable description of this Node's surface. */
    nodeMeta: (): Promise<Meta> =>
      call<Meta>('GET', '/v1/meta'),
    /** Every Society this Node holds. */
    societyList: (): Promise<SocietyList> =>
      call<SocietyList>('GET', '/v1/societies'),
    /** Found a Society. */
    societyCreate: (body: CreateSocietyRequest): Promise<SocietyEnvelope> =>
      call<SocietyEnvelope>('POST', '/v1/societies', body),
    /** Read one Society. */
    societyGet: (societyId: string): Promise<SocietyEnvelope> =>
      call<SocietyEnvelope>('GET', `/v1/societies/${societyId}`),
  };
}

export type FractalClient = ReturnType<typeof createClient>;
